version: '3.8'
services:
  praetor-api-service: # Nome do serviço dentro da stack
    build: .
    ports:
      - "3001:3000" # Mapeia a porta 3001 do host para a 3000 do contêiner
    restart: unless-stopped
    environment:
      - API_KEY=AIzaSyCJns5JfhcVa6wepwcUCaVnkhnD-JFxP4U
